name: rust ci

on:
  push:
    branches:
      - main
      - spire
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: run cargo check
        run: cargo build

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: run cargo test
        run: cargo test

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: [check, test]
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: publish gribberish-spire-types
        run: cargo publish -p gribberish-spire-types
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: publish gribberish-spire-macros
        run: cargo publish -p gribberish-spire-macros
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: publish gribberish-spire
        run: cargo publish -p gribberish-spire
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
